[workspace]
resolver = "2"
members = ["crates/dd-core", "src-tauri"]

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/DigitalDrivers/dd-desktop"

# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
